services:
  # hr-api:
  #   image: hrapi:v0.1
  #   ports:
  #     - 9091:80
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: TokyoJoe138!

  mongo-express:
    image: mongo-express:latest
    ports: 
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: TokyoJoe138!
      ME_CONFIG_MONGODB_SERVER: mongo
      # ME_CONFIG_ENABLE_ADMIN=true
    restart:
      always
    depends_on: 
      - mongo